### ISSUE TITLE
flutter_riverpod this library must be used?

### ISSUE THREAD

**Issue by trvaelmq** [FlexiKline/FlexiKline#1]
I don't quite know how to initialize it. Looking at your demo, you must use this.

**Comment by kangqiao** [comment]
Not required

riverpod is just a library for state management in flutter

You can also use Flutter setState to manage the state of FlexiKlineController, or use other state management libraries.

We will consider expanding the different states in the Controller in the future, and you can directly monitor a state and use it.

Stay tuned.

[TODO](https://github.com/FlexiKline/FlexiKline/blob/main/TODO.md)

**Comment by trvaelmq** [comment]
ok.Thank you very much, your library is great, but will you release the depth map, or is it available now? I don't see it in the sample.

**Comment by kangqiao** [comment]
We will consider adding depth maps in the future.
Currently, we are mainly working on drawing functions and performance optimization.
v1.0.0 will be a stable version
