### ISSUE TITLE
v0.8.0 & demo

### ISSUE THREAD

**Issue by beijibeijing** [FlexiKline/FlexiKline#2]
现在这个版本demo没了？v0.8.0啥时候出啊~

**Comment by kangqiao** [comment]
demo已拆分出去, 后续开放.
v0.8.0是框架优化版本, 预计12月份开发完成.

**Comment by beijibeijing** [comment]
请问demo也会在12月开放么？

**Comment by beijibeijing** [comment]
1.0估计啥时候出来啊？

**Comment by kangqiao** [comment]
感谢关注FlexiKline, v1.0 预计春节后.
项目是个人业余时间写的, 占用了大量休息时间, 不会很快的.
API和整体的框架会在v1.0稳定, 不会再做大的改动, 敬请期待.

**Comment by kangqiao** [comment]
感谢关注 FlexiKline！v1.0 预计春节后完成。
项目是我在个人业余时间写的，占用了大量休息时间，因此进度不会很快。
API和整体框架将在 v1.0 版本稳定后不再进行大的改动。敬请期待。
